[package]
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
edition = "2021"
name = "fe-compiler-test-utils"
version = "0.19.1-alpha"
license = "GPL-3.0-or-later"
repository = "https://github.com/ethereum/fe"

[dependencies]
ethabi = "17.0"
evm = "0.35.0"
evm-runtime = "0.35.0"
fe-common = {path = "../common", version = "^0.19.1-alpha"}
fe-driver = {path = "../driver", version = "^0.19.1-alpha"}
fe-yulc = {path = "../yulc", version = "^0.19.1-alpha", optional = true, features = ["solc-backend"]}
fe-analyzer = {path = "../analyzer", version = "^0.19.1-alpha"}
test-files = {path = "../test-files", package = "fe-test-files" }
hex = "0.4"
primitive-types = {version = "0.11.1", default-features = false, features = ["rlp"]}
serde_json = "1.0.64"
solc = {git = "https://github.com/cburgdorf/solc-rust", rev = "75ed40e", optional = true}
yultsur = {git = "https://github.com/g-r-a-n-t/yultsur", rev = "ae85470"}
indexmap = "1.6.2"
insta = "1.7.1"

# used by ethabi, we need to force the js feature for wasm support
getrandom = { version = "0.2.3", features = ["js"] }

[features]
solc-backend = ["fe-yulc", "solc", "fe-driver/solc-backend"]
