[package]
name = "fe-parser"
version = "0.19.1-alpha"
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ethereum/fe"
description = "Parser lib for Fe."

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fe-common = {path = "../common", version = "^0.19.1-alpha"}
logos = { version = "0.12.0", default-features = false, features = ["export_derive"] }
serde = { version = "1", features = ["derive"] }
unescape = "0.1.0"
vec1 = { version = "1.8.0", features = ["serde"] }
if_chain = "1.0.1"
semver = "1.0.0"
indenter = "0.3"
smol_str = "0.1.21"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"

[dev-dependencies]
fe-test-files = {path = "../test-files", version = "^0.19.1-alpha"}
insta = "1.7.1"
wasm-bindgen-test = "0.3"
pretty_assertions = "1.0.0"
criterion = "0.3.5"

[[bench]]
name = "bench"
harness = false
